clearvars -except ans
close all
clc


excelFile = 'locomotion_relative_3dmotion.xlsx';
sheetNames = { ...
    'C', ...
    'Full_inchworm', ...
    'Hybrid_inchworm'};

gaitNames = { ...
    'Hybrid Sidewinding', ...
    'Hybrid Concertina', ...
    'Concertina'};

outputName = 'HUTS_translation_box_whisker_IJRR_3gaits_clean_mean';

% Figure size.
figWidth  = 6;   % inches
figHeight = 5;   % inches

% Y-axis range.
yLim = [0 0.065];

% spacing compared 
pairSeparation  = 0.26;   % E1-E2 spacing within each gait
groupSeparation = 0.8;    % spacing between gait centers
boxWidth        = 0.22;

% Set up for font
fontName   = 'Times New Roman';
fontSize   = 10;
fontWeight = 'bold';

% Earth tones 
end1Color = [145 123 105]/255;
end2Color = [90 94 73]/255;

edgeColor    = [0.10 0.10 0.10];
medianColor  = [0.10 0.10 0.10];
outlierColor = [0.20 0.20 0.20];


meanMarkerSize = 6;
meanLabelOffset = 0.0015;

% read and write excel
if ~isfile(excelFile)
    error('Could not find "%s" in the current MATLAB folder.',excelFile);
end

nGaits = numel(sheetNames);

end1Data = cell(nGaits,1);
end2Data = cell(nGaits,1);

for g = 1:nGaits

    T = readtable( ...
        excelFile, ...
        'Sheet',sheetNames{g}, ...
        'VariableNamingRule','preserve', ...
        'Range','A4');

    % Keep only actual measurement rows.
    startFrame = str2double(string(T.('Start frame')));
    validRows = ~isnan(startFrame);
    T = T(validRows,:);

    E1 = str2double(string(T.('End1 Translation (BL/s)')));
    E2 = str2double(string(T.('End2 Translation (BL/s)')));

    E1 = E1(~isnan(E1));
    E2 = E2(~isnan(E2));

    % It only removes a value essentially equal to 0.08 BL/s.
    tol = 1e-6;
    E1(abs(E1 - 0.08) < tol) = [];
    E2(abs(E2 - 0.08) < tol) = [];

    end1Data{g} = E1;
    end2Data{g} = E2;
end

% Box plot build
allValues = [];
allGroups = [];
boxPositions = zeros(2*nGaits,1);

boxCounter = 0;

for g = 1:nGaits

    center = 1 + (g-1)*groupSeparation;

    posE1 = center - pairSeparation/2;
    posE2 = center + pairSeparation/2;

    boxCounter = boxCounter + 1;
    boxPositions(boxCounter) = posE1;

    allValues = [allValues; end1Data{g}(:)]; 
    allGroups = [allGroups; ...
        boxCounter*ones(numel(end1Data{g}),1)]; 

    boxCounter = boxCounter + 1;
    boxPositions(boxCounter) = posE2;

    allValues = [allValues; end2Data{g}(:)];
    allGroups = [allGroups; ...
        boxCounter*ones(numel(end2Data{g}),1)]; 
end

fig = figure( ...
    'Color','w', ...
    'Units','inches', ...
    'Position',[1 1 figWidth figHeight], ...
    'PaperPositionMode','auto');

ax = axes(fig);
hold(ax,'on');

boxplot( ...
    ax, ...
    allValues, ...
    allGroups, ...
    'Positions',boxPositions, ...
    'Widths',boxWidth, ...
    'Symbol','o', ...
    'Whisker',1.5, ...
    'Labels',repmat({' '},1,2*nGaits));

boxes    = findobj(ax,'Tag','Box');
medians  = findobj(ax,'Tag','Median');
whiskers = findobj(ax,'Tag','Whisker');
caps     = findobj(ax,'Tag','Cap');
outliers = findobj(ax,'Tag','Outliers');

set(boxes, ...
    'LineWidth',1.4, ...
    'Color',edgeColor);

set(medians, ...
    'LineWidth',1.6, ...
    'Color',medianColor);

set(whiskers, ...
    'LineWidth',1.2, ...
    'Color',edgeColor);

set(caps, ...
    'LineWidth',1.2, ...
    'Color',edgeColor);

set(outliers, ...
    'Marker','o', ...
    'MarkerSize',4, ...
    'MarkerEdgeColor',outlierColor);

for g = 1:nGaits

    dataPair  = {end1Data{g}, end2Data{g}};
    colorPair = {end1Color, end2Color};

    for e = 1:2

        k = 2*(g-1) + e;
        x0 = boxPositions(k);

        q1 = prctile(dataPair{e},25);
        q3 = prctile(dataPair{e},75);

        patch( ...
            ax, ...
            [x0-boxWidth/2, x0+boxWidth/2, ...
             x0+boxWidth/2, x0-boxWidth/2], ...
            [q1 q1 q3 q3], ...
            colorPair{e}, ...
            'FaceAlpha',0.55, ...
            'EdgeColor','none', ...
            'HandleVisibility','off');
    end
end

uistack(findobj(ax,'Tag','Box'),'top');
uistack(findobj(ax,'Tag','Median'),'top');
uistack(findobj(ax,'Tag','Whisker'),'top');
uistack(findobj(ax,'Tag','Cap'),'top');
uistack(findobj(ax,'Tag','Outliers'),'top');

% THis adds mean to plot 
for g = 1:nGaits

    dataPair  = {end1Data{g}, end2Data{g}};
    colorPair = {end1Color, end2Color};

    for e = 1:2

        k = 2*(g-1) + e;
        x0 = boxPositions(k);

        meanValue = mean(dataPair{e},'omitnan');

        plot( ...
            ax, ...
            x0, ...
            meanValue, ...
            'd', ...
            'MarkerSize',meanMarkerSize, ...
            'MarkerFaceColor',colorPair{e}, ...
            'MarkerEdgeColor','k', ...
            'LineWidth',1.0, ...
            'HandleVisibility','off');

        text( ...
            ax, ...
            x0, ...
            meanValue + meanLabelOffset, ...
            sprintf('%.3f',meanValue), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','bottom', ...
            'FontName',fontName, ...
            'FontSize',fontSize-1, ...
            'FontWeight',fontWeight, ...
            'Color','k', ...
            'Clipping','off');
    end
end

% Axis form
groupCenters = 1 + (0:nGaits-1)*groupSeparation;

xlim(ax,[groupCenters(1)-0.52, groupCenters(end)+0.52]);
ylim(ax,yLim);

ylabel(ax,'Translation Speed (BL/s)', ...
    'FontName',fontName, ...
    'FontSize',fontSize+1, ...
    'FontWeight',fontWeight);

xlabel(ax,'Locomotion Gait', ...
    'FontName',fontName, ...
    'FontSize',fontSize+1, ...
    'FontWeight',fontWeight);

% E1 / E2 tick labels.
set(ax, ...
    'XTick',boxPositions, ...
    'XTickLabel',repmat({'E_1','E_2'},1,nGaits), ...
    'TickLabelInterpreter','tex');

yl = ylim(ax);
labelY = yl(1) - 0.115*(yl(2)-yl(1));

for g = 1:nGaits
    text( ...
        ax, ...
        groupCenters(g), ...
        labelY, ...
        gaitNames{g}, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','top', ...
        'FontName',fontName, ...
        'FontSize',fontSize, ...
        'FontWeight',fontWeight, ...
        'Clipping','off');
end

set(ax, ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'FontWeight',fontWeight, ...
    'LineWidth',2, ...
    'TickDir','out', ...
    'TickLength',[0.012 0.012], ...
    'Box','off', ...
    'XGrid','off', ...
    'YGrid','off');

% leaving room
ax.Position = [0.12 0.22 0.85 0.73];


xl = xlim(ax);
yl = ylim(ax);

plot(ax, ...
    xl, ...
    [yl(2) yl(2)], ...
    'k-', ...
    'LineWidth',2, ...
    'HandleVisibility','off');

plot(ax, ...
    [xl(2) xl(2)], ...
    yl, ...
    'k-', ...
    'LineWidth',2, ...
    'HandleVisibility','off');

% LEGEND

hE1 = patch( ...
    ax,nan,nan,end1Color, ...
    'FaceAlpha',0.55, ...
    'EdgeColor',edgeColor, ...
    'LineWidth',1.2);

hE2 = patch( ...
    ax,nan,nan,end2Color, ...
    'FaceAlpha',0.55, ...
    'EdgeColor',edgeColor, ...
    'LineWidth',1.2);

leg = legend( ...
    ax, ...
    [hE1 hE2], ...
    {'End 1','End 2'}, ...
    'Location','northwest', ...
    'Box','off', ...
    'FontName',fontName, ...
    'FontSize',fontSize);

set(leg,'FontWeight',fontWeight);
